### ISSUE TITLE
数据集使用问题

### ISSUE THREAD

**Issue by maxinji** [WestlakeIntelligentRobotics/M3D#2]
M3D-Real数据集分成了两个子集，THE CROSS-CAMERA ADAPTATION PERFORMANCE OF DIFFERENT METHODS表格里的测试方法怎么应用这个数据集的，训练集、测试集以及验证集是怎么划分的

**Comment by OliviaZhang1996** [comment]
相关的training.txt, validation.txt和testing.txt我已经在数据集中提供
